name: reusable-original
on:
  workflow_call:
    secrets:
      MYSECRET:
        required: false
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      S: ${{ secrets.MYSECRET }}
    steps:
      - run: |
          echo "ORIGINAL REUSABLE WORKFLOW RAN"
          echo "secret length: ${#S}"
